version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run check
          command: npm run check
      - run:
          name: npm test
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
