name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push development image
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCP_ACCESS_DEVELOPMENT }}
          registry: gcr.io
          repository: automation-cloud-development/protocol
          tags: ${{ github.sha }}

      - name: Build and push production image
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCP_ACCESS_PRODUCTION }}
          registry: gcr.io
          repository: automation-cloud-production/protocol
          tags: ${{ github.sha }}

      - name: Notify k8s repo
        uses: docker://automationcloud/repository-dispatch:latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: ubio
          repository: k8s
          event: built-protocol
          payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: docker://automationcloud/rsslack:latest
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          message: ":success: Protocol has been built and <https://github.com/ubio/k8s|k8s> has been notified. Deployment incoming..."
          slack_token: ${{ secrets.SLACK_TOKEN }}

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: docker://automationcloud/rsslack:latest
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          message: ":suspicious: Protocol build failed"
          slack_token: ${{ secrets.SLACK_TOKEN }}
